### PR TITLE
Safety when we get an error during transaction begin

### LINKED ISSUE #18: UnboundLocalError: local variable 'tx' referenced before assignment
```python traceback
>>  result = TransactionLoop.__call__(self, request) # not super() for speed
Module nti.transactions.transactions:573 in __call__
>>  retryable = self._retryable(tx, exc_info)
UnboundLocalError: local variable 'tx' referenced before assignment
```

### PR DESCRIPTION
**Pull request by jzuech3**
Resolves #18

### CODE REVIEW

**Comment by jamadden** [comment]
Conflicts with the more extensive changes in #21, which should also fix #18. (The cause of #18 was the `del tx`, not it being 'None'.)

**Comment by jzuech3** [comment]
Agreed. Merge that first. Even if we remove the `del tx`, we'll need to handle tx being None in `_retryable`.

**Comment by jamadden** [comment]
Nah, if `txm.begin()` fails, something terrible happened. It's unlikely that it'd be a retryable exception. That just needs to be outside the scope of the retry logic. (RelStorage even has special logic to make sure that if something retryable *does* happen during `txm.begin()` -> `Connection.newTransaction` -> `storage.poll_invalidations()` it gets deferred until later; no one expects `txm.begin()` to fail. Which, now that I think about, may be slightly incomplete in newer versions...)

**Comment by jzuech3** [comment]
Ah, ok. We can probably delete this PR then. #18 was caused by an issue during `tx.begin` right?

**Comment by jamadden** [comment]
>  #18 was caused by an issue during tx.begin right?

Possibly, but not necessarily. There used to be `del tx` while we were still inside the scope of the `try/except` handler, and the arrival of a signal, say, could happen *after* `del tx` but before exiting the `try/except` block. Other conditions detected by the VM like `MemoryError` could also happen in that window.

**Pull request closed without merging**
